// Code generated by "enumer -type HTTPMethod -trimprefix Method -json -text"; DO NOT EDIT.

package urtypes

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _HTTPMethodName = "HEADGETPOSTPUTPATCHDELETEOPTIONS"

var _HTTPMethodIndex = [...]uint8{0, 4, 7, 11, 14, 19, 25, 32}

const _HTTPMethodLowerName = "headgetpostputpatchdeleteoptions"

func (i HTTPMethod) String() string {
	i -= 1
	if i >= HTTPMethod(len(_HTTPMethodIndex)-1) {
		return fmt.Sprintf("HTTPMethod(%d)", i+1)
	}
	return _HTTPMethodName[_HTTPMethodIndex[i]:_HTTPMethodIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _HTTPMethodNoOp() {
	var x [1]struct{}
	_ = x[MethodHEAD-(1)]
	_ = x[MethodGET-(2)]
	_ = x[MethodPOST-(3)]
	_ = x[MethodPUT-(4)]
	_ = x[MethodPATCH-(5)]
	_ = x[MethodDELETE-(6)]
	_ = x[MethodOPTIONS-(7)]
}

var _HTTPMethodValues = []HTTPMethod{MethodHEAD, MethodGET, MethodPOST, MethodPUT, MethodPATCH, MethodDELETE, MethodOPTIONS}

var _HTTPMethodNameToValueMap = map[string]HTTPMethod{
	_HTTPMethodName[0:4]:        MethodHEAD,
	_HTTPMethodLowerName[0:4]:   MethodHEAD,
	_HTTPMethodName[4:7]:        MethodGET,
	_HTTPMethodLowerName[4:7]:   MethodGET,
	_HTTPMethodName[7:11]:       MethodPOST,
	_HTTPMethodLowerName[7:11]:  MethodPOST,
	_HTTPMethodName[11:14]:      MethodPUT,
	_HTTPMethodLowerName[11:14]: MethodPUT,
	_HTTPMethodName[14:19]:      MethodPATCH,
	_HTTPMethodLowerName[14:19]: MethodPATCH,
	_HTTPMethodName[19:25]:      MethodDELETE,
	_HTTPMethodLowerName[19:25]: MethodDELETE,
	_HTTPMethodName[25:32]:      MethodOPTIONS,
	_HTTPMethodLowerName[25:32]: MethodOPTIONS,
}

var _HTTPMethodNames = []string{
	_HTTPMethodName[0:4],
	_HTTPMethodName[4:7],
	_HTTPMethodName[7:11],
	_HTTPMethodName[11:14],
	_HTTPMethodName[14:19],
	_HTTPMethodName[19:25],
	_HTTPMethodName[25:32],
}

// HTTPMethodString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func HTTPMethodString(s string) (HTTPMethod, error) {
	if val, ok := _HTTPMethodNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _HTTPMethodNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to HTTPMethod values", s)
}

// HTTPMethodValues returns all values of the enum
func HTTPMethodValues() []HTTPMethod {
	return _HTTPMethodValues
}

// HTTPMethodStrings returns a slice of all String values of the enum
func HTTPMethodStrings() []string {
	strs := make([]string, len(_HTTPMethodNames))
	copy(strs, _HTTPMethodNames)
	return strs
}

// IsAHTTPMethod returns "true" if the value is listed in the enum definition. "false" otherwise
func (i HTTPMethod) IsAHTTPMethod() bool {
	for _, v := range _HTTPMethodValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for HTTPMethod
func (i HTTPMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for HTTPMethod
func (i *HTTPMethod) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("HTTPMethod should be a string, got %s", data)
	}

	var err error
	*i, err = HTTPMethodString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for HTTPMethod
func (i HTTPMethod) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for HTTPMethod
func (i *HTTPMethod) UnmarshalText(text []byte) error {
	var err error
	*i, err = HTTPMethodString(string(text))
	return err
}
