# permissions for end users to edit accounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: account-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: uptime-robot-operator
    app.kubernetes.io/part-of: uptime-robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: account-editor-role
rules:
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - accounts/status
  verbs:
  - get
