# This rule is not used by the project uptime-robot-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to uptime-robot.clevyr.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: uptime-robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: monitor-viewer-role
rules:
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - monitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - monitors/status
  verbs:
  - get
