---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - accounts/finalizers
  verbs:
  - update
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - contacts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - contacts/finalizers
  verbs:
  - update
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - contacts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - monitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - monitors/finalizers
  verbs:
  - update
- apiGroups:
  - uptime-robot.clevyr.com
  resources:
  - monitors/status
  verbs:
  - get
  - patch
  - update
