apiVersion: uptime-robot.clevyr.com/v1
kind: Contact
metadata:
  labels:
    app.kubernetes.io/name: uptime-robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: example
spec:
  isDefault: true
  contact:
    friendlyName: "Slack #outages"
